title: Personal
description: Cool theme for your Github site

lang: en-US
branch: main

github: [metadata]

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata

theme: null

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - jekyll-theme-personal.gemspec
