# This config file is essential 
title: My Website
description: Cool theme for your Github site

# Before changing the lang parameter, ensure you new value is valid with:
# https://schneegans.de/lv/
lang: en-US

# Permalink structure
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title/

# Using TZ format, the list of all available values can be found at:
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: "Europe/Paris"

# The branch where the 
branch: main

# Ensure the encoding is UTF-8.
encoding: utf-8

# Ability to publish posts or collection documents with a future date.
future: true

# Ensure that metadata will be available at site level.
github: [metadata]

# Sass/SCSS parameters
# Use "expanded" for easy CSS debugging
# and "compressed" otherwise.
sass:
  style: expanded

# Pagination parameters
paginate: 10
paginate_path: /page:num/

# Code highligther
highlighter: rouge

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Exclude these files from production site
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .editorconfig
  - docs/
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CHANGELOG.md
  - CNAME
  - dracaena-theme.gemspec
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png

# Jekyll plugins used by the theme
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-github-metadata

# Theme name used in the build process
theme: BenSouchet/cyathea
