#!/bin/sh

set -e

scripts/build
bundle exec htmlproofer _site \
  --disable-external \
  --check-html \
  --report-missing-names \
  --report-script-embeds
bundle exec rubocop -D --config .rubocop.yml
bundle exec scripts/validate-html
gem build jekyll-theme-personal.gemspec
